repos:
  - repo: "https://github.com/domluna/JuliaFormatter.jl"
    rev: "v2.1.5"
    hooks:
    - id: "julia-formatter"
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: mixed-line-ending